# Setup
title:               Alessandro Nardin
tagline:             'Page for Google Summer of Code 2024'
description:         ''
url:                 https://alessandronardin.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alessandro Nardin
  email:             ale.daluch@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
