title: Alessandro Nardin
tagline: Personal Portfolio
email: ale.daluch@gmail.com
baseurl: "" # leave empty if you're using a user/organization repo, else use "/repo-name"
url: "https://alessandronardin.github.io" # change if you're using a custom domain
twitter_username: jekyllrb
github_username: AlessandroNardin

# Build settings
theme: null # we’re using a manual theme (Lanyon), not a gem theme
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Pagination (only works if you enable it via plugin and layout)
# paginate: 5
# paginate_path: "/page:num"

# Optional: Exclude stuff you don’t want published
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules/
  - vendor/
  - .gitignore
  - .editorconfig
